apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hive-metastore
  name: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: hive-metastore
          image: bde2020/hive:2.3.2-postgresql-metastore
          envFrom:
            - configMapRef:
                name: hive-config
          ports:
            - containerPort: 9083
              protocol: TCP
          command: ["/opt/hive/bin/hive"]
          args: ["--service", "metastore"]
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hive-metastore-postgresql
  name: hive-metastore-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore-postgresql
  template:
    metadata:
      labels:
        app: hive-metastore-postgresql
    spec:
      containers:
        - name: hive-metastore-postgresql
          image: bde2020/hive-metastore-postgresql:2.3.0
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: hive-metastore-postgresql
      restartPolicy: Always
      volumes:
        - name: hive-metastore-postgresql
          persistentVolumeClaim:
            claimName: hive-metastore-postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trino
  name: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino
  template:
    metadata:
      labels:
        app: trino
    spec:
      containers:
        - name: trino
          image: trinodb/trino:457
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/lib/trino/etc
              name: trino-cm0
            - mountPath: /etc/trino/catalog
              name: trino-cm1
      restartPolicy: Always
      volumes:
        - configMap:
            name: trino-cm0
          name: trino-cm0
        - configMap:
            name: trino-cm1
          name: trino-cm1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: superset
  name: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
        - name: superset
          image: tranngocbao126/superset
          env:
            - name: SUPERSET_SECRET_KEY
              value: secret
            - name: SUPERSET_PORT
              value: "8088"
          ports:
            - containerPort: 8088
              protocol: TCP
          volumeMounts:
            - mountPath: /app/superset_home
              name: superset-data
      restartPolicy: Always
      volumes:
        - name: superset-data
          persistentVolumeClaim:
            claimName: superset-data
