apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: airflow-init
  name: airflow-init
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airflow-init
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: airflow-init
    spec:
      containers:
        - args:
            - version
          env:
            - name: AIRFLOW__API__AUTH_BACKEND
              value: airflow.api.auth.backend.basic_auth
            - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
              value: "true"
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__CORE__FERNET_KEY
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "false"
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflow@postgres/airflow
            - name: _AIRFLOW_DB_UPGRADE
              value: "true"
            - name: _AIRFLOW_WWW_USER_CREATE
              value: "true"
            - name: _AIRFLOW_WWW_USER_PASSWORD
              value: airflow
            - name: _AIRFLOW_WWW_USER_USERNAME
              value: airflow
            - name: _PIP_ADDITIONAL_REQUIREMENTS
              value: ' apache-airflow-providers-microsoft-mssql'
          image: airflow-init
          name: airflow-init
          volumeMounts:
            - mountPath: /opt/airflow/logs
              name: airflow-logs
            - mountPath: /opt/airflow/plugins
              name: airflow-plugins
            - mountPath: /opt/airflow/scripts
              name: airflow-scripts
            - mountPath: /opt/airflow/spark
              name: airflow-init-cm4
            - mountPath: /opt/airflow/source
              name: airflow-init-cm5
      restartPolicy: Always
      volumes:
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: airflow-logs
        - name: airflow-plugins
          persistentVolumeClaim:
            claimName: airflow-plugins
        - name: airflow-scripts
          persistentVolumeClaim:
            claimName: airflow-scripts
        - configMap:
            name: airflow-init-cm4
          name: airflow-init-cm4
        - configMap:
            name: airflow-init-cm5
          name: airflow-init-cm5
