apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: airflow-plugins
  name: airflow-plugins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
