apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: hadoop-datanode3
  name: hadoop-datanode3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
