apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: hive-metastore-postgresql
  name: hive-metastore-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
