apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: superset
  name: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: superset
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: superset
    spec:
      containers:
        - env:
            - name: SUPERSET_SECRET_KEY
              value: secret
          image: superset
          name: superset
          ports:
            - containerPort: 8088
              protocol: TCP
          volumeMounts:
            - mountPath: /app/superset_home
              name: superset-data
      restartPolicy: Always
      volumes:
        - name: superset-data
          persistentVolumeClaim:
            claimName: superset-data
