apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: trino
  name: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: trino
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: trino
    spec:
      containers:
        - image: trinodb/trino:457
          name: trino
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/lib/trino/etc
              name: trino-cm0
              readOnly: true
            - mountPath: /etc/trino/catalog
              name: trino-cm1
      restartPolicy: Always
      volumes:
        - configMap:
            name: trino-cm0
          name: trino-cm0
        - configMap:
            name: trino-cm1
          name: trino-cm1
