apiVersion: v1
kind: Service
metadata:
  name: {{ include "hiveMetastore.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "hiveMetastore.name" . }}
    app.kubernetes.io/component: server
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: thrift
      protocol: TCP
      name: thrift
  selector:
    app.kubernetes.io/name: {{ template "hiveMetastore.name" . }}
    app.kubernetes.io/component: server
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
