#Docker Compose For Ranger with Postgres Built in
version: "2"

services:
  ranger:
    build: ranger
    ports:
      - "6182:6182"
      - "6083:6083"
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      -  ./env
    volumes:
      - /etc/security/pki:/security
      - /etc/pki/java/:/etc/pki/java/
      - solr:/opt/solr/data
  postgres:
    build: postgres
    ports:
      - 5432
    env_file:
      -  ./env
    volumes:
      - db:/var/lib/pgsql/data/

volumes:
  db:
  solr:
